### ISSUE TITLE
update to 0.2.1

### ISSUE THREAD

**Issue by pmeier** [conda-forge/ragna-feedstock#1]
@kklein [v0.2.1](https://github.com/Quansight/ragna/releases/tag/v0.2.1) is out. Could you update the recipe? IIRC, there was a bot that could do this automatically? But I haven't maintained a feedstock in a while so I don't know for sure.

**Comment by kklein** [comment]
Hi @pmeier ! Thanks for brining this to my attention. Usually a bot picks it up from PyPI in <24h indeed. This might be related to https://github.com/conda-forge/status/issues/181 - not sure.

Will take a look!

**Comment by kklein** [comment]
@pmeier https://anaconda.org/conda-forge/ragna/files :)

**Comment by pmeier** [comment]
Awesome :tada: Is the process now automated?

**Comment by kklein** [comment]
Afaict yes and afaict the automated process was just down over the past couple of days.
